"""empty message

Revision ID: 049bb2ac2b92
Revises: d26193d7e814
Create Date: 2017-10-03 00:34:37.617833

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '049bb2ac2b92'
down_revision = 'd26193d7e814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_owners', 'owners', ['email', 'user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_owners', 'owners', type_='unique')
    # ### end Alembic commands ###
