"""empty message

Revision ID: 2edaa8105387
Revises: bb7eb4e8833a
Create Date: 2017-09-27 17:49:06.780496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2edaa8105387'
down_revision = 'bb7eb4e8833a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link_check', sa.Column('job_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'link_check', 'scan_job', ['job_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'link_check', type_='foreignkey')
    op.drop_column('link_check', 'job_id')
    # ### end Alembic commands ###
