"""empty message

Revision ID: 31a9133ed7e7
Revises: 
Create Date: 2017-09-26 18:50:59.257460

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '31a9133ed7e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_check',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('response', sa.Integer(), nullable=True),
    sa.Column('headers', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_link_check_response'), 'link_check', ['response'], unique=False)
    op.create_index(op.f('ix_link_check_url'), 'link_check', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_link_check_url'), table_name='link_check')
    op.drop_index(op.f('ix_link_check_response'), table_name='link_check')
    op.drop_table('link_check')
    # ### end Alembic commands ###
