"""empty message

Revision ID: 32118aff73c2
Revises: fc9b10810963
Create Date: 2017-10-01 13:45:32.872519

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '32118aff73c2'
down_revision = 'fc9b10810963'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_job', sa.Column('status', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_job', 'status')
    # ### end Alembic commands ###
