"""empty message

Revision ID: 541f5b614863
Revises: f6698d3ecde4
Create Date: 2017-10-15 08:40:44.570652

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '541f5b614863'
down_revision = 'f6698d3ecde4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exception',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exception', sa.Text(), nullable=True),
    sa.Column('exception_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exception_exception'), 'exception', ['exception'], unique=True)
    op.create_index(op.f('ix_exception_exception_description'), 'exception', ['exception_description'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exception_exception_description'), table_name='exception')
    op.drop_index(op.f('ix_exception_exception'), table_name='exception')
    op.drop_table('exception')
    # ### end Alembic commands ###
