"""empty message

Revision ID: 58bbeea63691
Revises: 32118aff73c2
Create Date: 2017-10-01 15:51:14.797897

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '58bbeea63691'
down_revision = '32118aff73c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissioned_url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('root_url', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('owner', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('root_url', 'user_id', 'owner', name='unique_urls_per_userowner')
    )
    op.create_index(op.f('ix_permissioned_url_owner'), 'permissioned_url', ['owner'], unique=False)
    op.create_index(op.f('ix_permissioned_url_root_url'), 'permissioned_url', ['root_url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissioned_url',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"permissioned_url_id_seq"\'::regclass)'), nullable=False),
    sa.Column('root_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('owner', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='permissioned_url_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='permissioned_url_pkey'),
    sa.UniqueConstraint('root_url', 'user_id', 'owner', name='unique_urls_per_userowner')
    )
    op.drop_index(op.f('ix_permissioned_url_root_url'), table_name='permissioned_url')
    op.drop_index(op.f('ix_permissioned_url_owner'), table_name='permissioned_url')
    op.drop_table('permissioned_url')
    # ### end Alembic commands ###
