"""empty message

Revision ID: 61e0ec503993
Revises: 295bf8bcc92d
Create Date: 2017-09-30 12:37:42.461192

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '61e0ec503993'
down_revision = '295bf8bcc92d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_job', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'scan_job', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scan_job', type_='foreignkey')
    op.drop_column('scan_job', 'user_id')
    # ### end Alembic commands ###
