"""empty message

Revision ID: 7ec5f50a2bb2
Revises: dca997e4d617
Create Date: 2017-10-11 08:29:34.350361

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7ec5f50a2bb2'
down_revision = 'dca997e4d617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('link', 'job_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('link_check', 'job_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('owners', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('permissioned_url', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('permissioned_url', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('scan_job', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('scan_job', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('scan_job', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('scheduled_job', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('scheduled_job', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scheduled_job', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('scheduled_job', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('scan_job', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('scan_job', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('scan_job', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('permissioned_url', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('permissioned_url', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('owners', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('link_check', 'job_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('link', 'job_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
