"""empty message

Revision ID: bb7eb4e8833a
Revises: 371b3d91e616
Create Date: 2017-09-27 17:38:41.147424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb7eb4e8833a'
down_revision = '371b3d91e616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('root_url', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_job_root_url'), 'scan_job', ['root_url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_job_root_url'), table_name='scan_job')
    op.drop_table('scan_job')
    # ### end Alembic commands ###
