"""empty message

Revision ID: d26193d7e814
Revises: daafe4c04b38
Create Date: 2017-10-03 00:29:01.574702

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd26193d7e814'
down_revision = 'daafe4c04b38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owners', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'owners', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'owners', type_='foreignkey')
    op.drop_column('owners', 'user_id')
    # ### end Alembic commands ###
