"""empty message

Revision ID: dca997e4d617
Revises: a942e619bd00
Create Date: 2017-10-04 20:24:12.968863

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dca997e4d617'
down_revision = 'a942e619bd00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissioned_url', sa.Column('stripe_subscription_id', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permissioned_url', 'stripe_subscription_id')
    # ### end Alembic commands ###
