"""empty message

Revision ID: f6698d3ecde4
Revises: 7ec5f50a2bb2
Create Date: 2017-10-14 15:39:32.446203

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f6698d3ecde4'
down_revision = '7ec5f50a2bb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link_check', sa.Column('exception', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_link_check_exception'), 'link_check', ['exception'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_link_check_exception'), table_name='link_check')
    op.drop_column('link_check', 'exception')
    # ### end Alembic commands ###
