"""empty message

Revision ID: fc9b10810963
Revises: 61e0ec503993
Create Date: 2017-09-30 23:02:34.836000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fc9b10810963'
down_revision = '61e0ec503993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('root_url', sa.Text(), nullable=True),
    sa.Column('owner', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_job_owner'), 'scheduled_job', ['owner'], unique=False)
    op.create_index(op.f('ix_scheduled_job_root_url'), 'scheduled_job', ['root_url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_job_root_url'), table_name='scheduled_job')
    op.drop_index(op.f('ix_scheduled_job_owner'), table_name='scheduled_job')
    op.drop_table('scheduled_job')
    # ### end Alembic commands ###
